#!/usr/bin/env bash
# Fedora Workstation Setup
# WARNING: This is a personal installation script.
# Please review this script and adjust it to your needs prior to running it.
# This script is intended for a minimal Fedora Workstation installation on a Thinkpad
# run as root:
# curl https://raw.githubusercontent.com/bridgesense/dotfiles/master/awesomewm/awesome-on-silverblue > custom-fedora-setup
# $SHELL sudo custom-fedora-setup <username>
# # # # # # # # # # # # # # #

# Options
# # # # # # # # # # # # # # #
USER="${1:francis}"
LOGFILE="/var/home/$USER/workstation-installation.log"

# Functions
# # # # # # # # # # # # # # #
function log {
    if [ -f "$LOGFILE" ]; then
        echo $1 >> $LOGFILE
    else
        echo $1 > $LOGFILE
    fi
}

function install {
    arr=("$@")
    _type=
    if [[ "$(declare -p arr)" =~ "declare -a" ]]; then
        for package in "${arr[@]}"; do
            cnt=3
            while [ $cnt -gt 0 ]; do
                if sudo rpm-ostree db diff | grep $package > /dev/null 2>&1; then
                    break;
                else
                   sudo rpm-ostree install $package
                fi
                let "cnt-=1"
            done
            if ! sudo rpm-ostree db diff | grep $package > /dev/null 2>&1; then
                log "There was a problem installing ${package}.  Please make sure this package exists."
            fi
        done
    else
        log "Warning! Passed variable is not an array".
    fi
}

install htop
