#!/usr/bin/env bash
# Fedora Workstation Setup
# WARNING: This is a personal installation script.
# DANGER: This is a test script.  Please don't use it.  The rpm-ostree is really not designed to handle heavy customizations yet.  A few more pockets and repositories are needed.
# Please review this script and adjust it to your needs prior to running it.
# This script is intended for a minimal Fedora Workstation installation on a Thinkpad
# run as root:
# curl https://raw.githubusercontent.com/bridgesense/dotfiles/master/awesomewm/install-awesome-silverblue > custom-fedora-setup
# # install command line tools
# sudo $SHELL custom-fedora-setup <username> toolbox
# # install awesome wm
# sudo $SHELL custom-fedora-setup <username> awesome
# # # # # # # # # # # # # # #
if [[ "${USER}" != "root" ]]; then
   echo "this script must be run with sudo"
   exit
fi

# Options
# # # # # # # # # # # # # # #
USER="${1:francis}"
INSTALL="${2:toolbox}"
LOGFILE=/var/home/$USER/workstation-installation.log

# Functions
# # # # # # # # # # # # # # #
function log {
    if [ -f "$LOGFILE" ]; then
        su -c "echo $1 >> $LOGFILE" $USER
    else
        su -c "echo $1 > $LOGFILE" $USER
    fi
}

function install {
    arr=("$@")
    _type=
    _group=
    _cmd=
    _diff=
    if [[ "$(declare -p arr)" =~ "declare -a" ]]; then
        for package in "${arr[@]}"; do
 	    if [[ $package == "dnf" ]]; then
                _type=$package
                continue
            fi
            if [[ $package == "rpm-ostree" ]]; then
                _type=$package
                _diff="$(rpm-ostree db diff > /dev/null 2>&1)"
                continue
            fi
	    if [[ $package == "group" ]]; then
                _group=$package
                continue
            fi
            if [[ $_type == "dnf" ]]; then
                if dnf list installed $package > /dev/null 2>&1; then
                    continue;            
                else
                    _cmd="${_cmd} ${package}" 
		fi
            fi
            if [[ $_type == "rpm-ostree" ]]; then
               if [[ $_diff =~ "${package}" ]]; then
	           continue;
	       else
                   _cmd="${_cmd} ${package}" 
	       fi
	    fi
	    if [[ $package == "group" ]]; then
               _cmd="${_cmd} ${package}" 
            fi
        done
        if [[ $_type == "dnf" ]]; then
	    dnf install -y $_cmd
	fi 
	if [[ $_group == "group" ]]; then
	    dnf group install -y $_cmd
	fi
        if [[ $_type == "rpm-ostree" ]]; then
            rpm-ostree install --allow-inactive $_cmd
            _diff="$(rpm-ostree db diff > /dev/null 2>&1)"
        fi
        for package in "${arr[@]}"; do
 	    if [[ $package == "dnf" ]] || [[ $package == "rpm-ostree" ]] || [[ $package == "group" ]]; then
                continue;
            fi
            if [[ $_type == "rpm-ostree" ]]; then
               if [[ $_diff != *"${package}"* ]]; then
                    log "There was a problem installing ${package}.  Please make sure this package exists."
               fi
            fi
            if [[ $_type == "dnf" ]]; then
                if ! dnf list installed $package > /dev/null 2>&1 && [[ $_group != "group" ]]; then
                    log "There was a problem installing ${package}.  Please make sure this package exists."
                fi
	    fi
        done
    else
        log "Warning! Passed variable is not an array".
    fi
}

if [[ $INSTALL == "toolbox" ]]; then
if ! command -v dnf &> /dev/null; then
   echo "Please create a toolbox and enter it before starting this script"
   echo "run: toolbox create -y"  
   echo "toolbox enter"
   exit
fi

# build the toolbox 
# # # # # # # # # # # # # # #
if ! command -v cmake &> /dev/null; then
log "installing commandline tools"
install dnf autoconf automake git rsync htop
install dnf group development-tools rpm-development-tools c-development 
dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
dnf update -y
# command line support
install dnf net-tools ftp telnet gnutls mailx wireless-tools
fi

# install/update dotfiles 
# # # # # # # # # # # # # # #
if [ -d "/var/home/$USER/.yadrlite" ]; then
    su -c "$SHELL /var/home/$USER/.yadrlite/setup update" $USER
else
    su -c '$SHELL -c "`curl -fsSL https://raw.githubusercontent.com/bridgesense/dotfiles/master/setup`"' $USER
fi

# install xbanish
# # # # # # # # # # # # # # #
su -c 'mkdir ~/.local/bin' $USER
if ! command -v xbanish &> /dev/null; then
log "installing xbanish"
install dnf libXt-devel libXfixes-devel libXi-devel
su -c 'git clone https://github.com/jcs/xbanish.git ~/lab/xbanish' $USER
su -c 'cd ~/lab/xbanish && make -C ~/lab/xbanish' $USER
sleep 1
su -c 'cp  ~/lab/xbanish/xbanish ~/.local/bin' $USER
su -c 'cd ~/lab/xbanish && make clean' $USER 
fi

# install code editors and PHP dev tools
# # # # # # # # # # # # # # #
if ! command -v tmux &> /dev/null; then
install dnf tmux the_silver_searcher ack tree w3m w3m-img expect hugo
# install ctags
install dnf python3-docutils libseccomp-devel jansson-devel libyaml-devel libxml2-devel
su -c "cd ~/lab && git clone https://github.com/universal-ctags/ctags.git" $USER
su -c "cd ~/lab/ctags && ./autogen.sh" $USER
su -c "cd ~/lab/ctags && ./configure --program-prefix=ex" $USER
su -c "cd ~/lab/ctags && make PREFIX=/var/home/$USER/.local/bin install && make clean" $USER
# neovim
install dnf python3-devel ruby-devel
su -c "pip install pynvim" $USER
su -c "gem install neovim" $USER
su -c "gem environment" $USER
su -c "npm install -g neovim" $USER
su -c "mkdir ~/.config/nvim && cp ~/.yadrlite/awesome/nvim/init.vim ~/.config/nvim" $USER
mkdir ~/.config/nvim && cp ~/.yadrlite/awesome/nvim/init.vim ~/.config/nvim
sed -i '/Default Prompt/a export EDITOR=nvim\nexport PAGER=less\nalias vi="nvim"\nalias vim="nvim"' /var/home/$USER/.bashrc
# screen adjustments 
su -c "pip install autorandr" $USER
# for alacritty
su -c "pip3 install pyyaml" $USER
# install bpytop
su -c "pip3 install bpytop --upgrade" $USER
# for ranger
su -c "pip3 install ueberzug" $USER
# grunt
su -c "npm install -g npm@latest" $USER
su -c "npm install -g grunt-cli coffee-jshint eslint js-yaml csslint" $USER
su -c 'gem update' $USER
su -c 'gem install compass' $USER
# composer
install dnf composer
fi

# compiles emacs 27
# for much better speed and compatibitily
# WARNING: emacs X11 will crash with pacakge: google-noto-emoji-color-fonts
# # # # # # # # # # # # # # #
if ! command -v emacs &> /dev/null; then
log "compiling emacs 27"
install dnf liblockfile-devel libotf-devel m17n-db-devel m17n-lib-devel gtk3-devel ncurses-devel gnutls-devel gnutls-utils
install dnf libXpm-devel libxml2-devel libjpeg-turbo-devel giflib-devel libtiff-devel texinfo
su -c 'git clone -b master git://git.sv.gnu.org/emacs.git ~/lab/emacs' $USER
# locks emacs into March 27th, 2020 release (stable)
su -c 'cd ~/lab/emacs && git checkout 6075a7c5ae3fa456cd099946f6e042b57e925263' $USER
sleep 1.5s
su -c 'cd ~/lab/emacs && ./autogen.sh' $USER
su -c "cd ~/lab/emacs && ./configure --without-makeinfo --with-gnutls=ifavailable --with-mailutils --prefix=/var/home/$USER/.local" $USER
su -c 'make -C ~/lab/emacs' $USER
su -c 'cd ~/lab/emacs && make install' $USER
su -c 'cd ~/lab/emacs && make clean' $USER
fi

# required modules for boris and phpctags
# # # # # # # # # # # # # # #
if ! command -v phpctags.phar &> /dev/null; then
log "installing phpctags"
install dnf ruby-devel
su -c 'git clone https://github.com/xcwen/phpctags.git ~/lab/phpctags' $USER
su -c 'make -C ~/lab/phpctags' $USER
su -c "cp /var/home/$USER/lab/phpcstags/build/phpctags.phar ~/.local/bin" $USER
fi

# leela
# # # # # # # # # # # # # # #
install dnf openblas-devel.x86_64 gtest-devel ninja-build meson
su -c 'cd ~/Applications && git clone -b release/0.24 --recurse-submodules https://github.com/LeelaChessZero/lc0.git' $USER
su -c 'cd ~/Applications/lc0 && $SHELL build.sh' $USER

# Bluray Playback
# # # # # # # # # # # # # # #
log "installing bluray playback"
install dnf ffmpeg-devel openssl-devel
su -c 'cd ~/lab && wget http://www.makemkv.com/download/makemkv-oss-1.15.3.tar.gz' $USER
su -c 'cd ~/lab && tar xpf makemkv-oss-1.15.3.tar.gz' $USER
su -c 'cd ~/lab/makemkv-oss-1.15.3 && ./configure' $USER
su -c 'make -C ~/lab/makemkv-oss-1.15.3' $USER
cd /var/home/$USER/lab/makemkv-oss-1.15.3 && make install PREFIX=/var/home/$USER/.local
su -c 'cd ~/lab && wget http://www.makemkv.com/download/makemkv-bin-1.15.3.tar.gz' $USER
su -c 'cd ~/lab && tar xpf makemkv-bin-1.15.3.tar.gz' $USER
su -c 'make -C ~/lab/makemkv-bin-1.15.3' $USER
cd /var/home/$USER/lab/makemkv-bin-1.15.3 && make install PREFIX=/var/home/$USER/.local
chown $USER:$USER -R /var/home/$USER/.local/bin

# end toolbox install
printf "Toolbox Installation complete."
printf "\r# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #\r"
fi


# Override Silverblue Gnome with Awesome WM 
# # # # # # # # # # # # # # #
if [[ $INSTALL == "awesome" ]]; then
log "installing supporting applications"
install rpm-ostree fontawesome-fonts xautolock i3lock lxappearance gdouros-symbola-fonts gucharmap xbacklight feh arc-theme redshift-gtk gtk-murrine-engine compton pulseeffects pavucontrol xclip vim-common arandr zenity flameshot gnome-keyring gnome-control-center NetworkManager-tui NetworkManager-wifi NetworkManager-openvpn-gnome NetworkManager-openconnect-gnome dhcp-client iw wpa_supplicant blueman sbc libnotify python3-httplib2 wordnet aspell-en texlive-latex texlive-collection-latex texlive-collection-latexextra papirus-icon-theme nemo fuse-exfat exfat-utils libmtp libmtp-examples gvfs-mtp acpi crontabs firewall-config system-config-printer simple-scan nomacs gnome-disk-utility atool cups hplip hplip-gui policycoreutils-gui setools-console setroubleshoot clamav clamav-update timeshift brasero neovim gnutls-utils obs-studio

# install awesome window manager nightly
# v4.3 stable has a pretty bad bug in the keygrabber
# that doesn't work well with this theme
# # # # # # # # # # # # # # #
wget https://copr.fedorainfracloud.org/coprs/jcrd/awesome-luajit-nightly/repo/fedora-33/jcrd-awesome-luajit-nightly-fedora-33.repo -P /etc/yum.repos.d/
install rpm-ostree awesome

# copy over system start resources
# # # # # # # # # # # # # # #
log "copying over system start resources"
su -c 'cp -f ~/.yadrlite/awesome/Xresources ~/.Xresources' $USER
cp -f ~/.yadrlite/awesome/Xresources ~/.Xresources
su -c 'mkdir -p ~/.config/awesome' $USER
su -c 'rsync -azhLP ~/.yadrlite/awesome/setup/ ~/.config/awesome' $USER
su -c 'git clone https://github.com/lcpz/awesome-freedesktop.git ~/.config/awesome/freedesktop' $USER
su -c 'git clone https://github.com/potamides/modalawesome.git ~/.config/awesome/modalawesome' $USER
# uncomment the following line to give Sudoers access to the user account
echo "pgrep 'tmux|start' || startx" >> /var/home/$USER/.bash_profile
# powerline font patch
su -c 'mkdir -p ~/.local/share/fonts/' $USER
su -c 'cd ~/.local/share/fonts && svn checkout https://github.com/powerline/fonts/trunk/DejaVuSansMono' $USER
fc-cache
# freedesktop repo implementation
su -c "git clone https://github.com/lcpz/awesome-freedesktop.git /var/home/$USER/.config/awesome/freedesktop" $USER
git clone https://github.com/lcpz/awesome-freedesktop.git ~/.config/awesome/freedesktop
git clone https://github.com/potamides/modalawesome.git ~/.config/awesome/modalawesome

# misc
su -c 'mkdir -p ~/Applications' $USER

# Install supporting applications
# # # # # # # # # # # # # # #
log "installing supporting applications"


# More themes
# # # # # # # # # # # # # # #
log "installing themes"
su -c 'git clone https://github.com/vinceliuice/Matcha-gtk-theme.git ~/lab/matcha' $USER
su -c 'cd ~/lab/matcha && bash install.sh' $USER

# install alacritty terminal
install rpm-ostree alacritty
su -c 'mkdir -p ~/.config/alacritty' $USER
su -c 'cp ~/.yadrlite/awesome/alacritty/* ~/.config/alacritty' $USER

# install ranger
install rpm-ostree caca-utils ffmpegthumbnailer unrar python3-bidict ranger
su -c "cp -r ~/.yadrlite/awesome/ranger ~/.config" $USER
cp -r ~/.yadrlite/awesome/ranger ~/.config

# backlight fix for i915 GPU's
# to work with cbacklight script
log "applying backlight fix for i915 GPU"
usermod -aG video $USER
echo "ACTION==\"add\", SUBSYSTEM==\"backlight\", KERNEL==\"intel_backlight\", RUN+=\"/bin/chgrp video /sys/class/backlight/%k/brightness\"" >> /etc/udev/rules.d/backlight.rules
echo "ACTION==\"add\", SUBSYSTEM==\"backlight\", KERNEL==\"intel_backlight\", RUN+=\"/bin/chmod g+w /sys/class/backlight/%k/brightness\"" >> /etc/udev/rules.d/backlight.rules
su -c "cp /var/home/$USER/.yadrlite/awesome/scripts/cbacklight ~/.local/bin/cbacklight"

# Add "tap to click" for touchpads
# # # # # # # # # # # # # # #
log "add 'tap to click' for touchpads"
cp /run/host/usr/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d
sed -i '/Identifier "libinput touchpad catchall"/a \\tOption "Tapping" "on"' /etc/X11/xorg.conf.d/40-libinput.conf

# blutooth headset fix for better audio quality
log "blutooth heaset fix for better audio quality"
sed -i 's/module-bluetooth-discover/module-bluetooth-discover headset=auto/' /etc/pulse/default.pa

# disable Wayland
log "disabling wayland"
mkdir -p /etc/gdm
cp /run/host/etc/gdm/custom.conf /etc/gdm/custom.conf
sed -i '/\[daemon\]/a WaylandEnable=false\nDefaultSession=gnome-xorg.desktop' /etc/gdm/custom.conf

# help the sound (for Thinkpads)
# # # # # # # # # # # # # # #
log "improving sound output for Thinkads"
echo "default-sample-format = float32le" >> /etc/pulse/daemon.conf
echo "default-sample-rate = 48000" >> /etc/pulse/daemon.conf
echo "alternate-sample-rate = 44100" >> /etc/pulse/daemon.conf
echo "default-fragments = 2" >> /etc/pulse/daemon.conf
echo "default-fragment-size-msec = 125" >> /etc/pulse/daemon.conf
echo "resample-method = soxr-vhq" >> /etc/pulse/daemon.conf
echo "remixing-produce-lfe = no" >> /etc/pulse/daemon.conf
echo "remixing-consume-lfe = no" >> /etc/pulse/daemon.conf
echo "high-priority = yes" >> /etc/pulse/daemon.conf
echo "realtime-scheduling = yes" >> /etc/pulse/daemon.conf
echo "realtime-priority = 9" >> /etc/pulse/daemon.conf
echo "rlimit-rtprio = 9" >> /etc/pulse/daemon.conf
echo "daemonize = no" >> /etc/pulse/daemon.conf

# set timezone
# # # # # # # # # # # # # # #
log "setting timezone to Pacific"
timedatectl set-timezone America/Los_Angeles

# enable thinkfan
# this is a sample config for a t460
# # # # # # # # # # # # # # #
log "enabling thinkfan"
install rpm-ostree thinkfan
HWMONDEV=`basename /sys/devices/platform/coretemp.0/hwmon/*`
sed -i "/55)/i \
hwmon /sys/devices/platform/coretemp.0/hwmon/${HWMONDEV}/temp3_input \n\
hwmon /sys/devices/platform/coretemp.0/hwmon/${HWMONDEV}/temp4_input \n\
hwmon /sys/devices/platform/coretemp.0/hwmon/${HWMONDEV}/temp1_input \n\
hwmon /sys/devices/platform/coretemp.0/hwmon/${HWMONDEV}/temp5_input \n\
hwmon /sys/devices/platform/coretemp.0/hwmon/${HWMONDEV}/temp2_input \n\
" /etc/thinkfan.conf

# RE: freezing issue on newer intel graphics when monitor idles
# ref: https://linuxreviews.org/Intel_graphics
echo "fix issue with intel graphics on newer machines"
echo "edit /etc/default/grub and add the following to GRUB_CMDLINE_LINUX"
echo "add ahci.mobile_lpm_policy=1 for recently released Lenovo Laptops"
echo "add i915.enable_dc=0 for Goldmount or Kaby Lake Processors"
echo "add intel_idle.max_cstate=1 for Bay Trail or Kaby Lake Processors"
echo "run the following as root:"
echo "grub2-mkconfig --output=/boot/efi/EFI/fedora/grub.cfg"
echo "after reboot, test by viewing "/proc/cmdline and search for your changes"

# install non-free firmware for compatibilty crises
log "installing non-free firmware"
rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
rpm-ostree update
install rpm-ostree alsa-ucm alsa-firmware alsa-tools alsa-firmware alsa-sof-firmware alsa-tools-firmware atmel-firmware bfa-firmware crystalhd-firmware gnome-firmware ipw2100-firmware ipw2200-firmware iscan-firmware ivtv-firmware iwl100-firmware iwl1000-firmware iwl105-firmware iwl135-firmware iwl2000-firmware iwl2030-firmware iwl3160-firmware iwl3945-firmware iwl4965-firmware iwl5000-firmware iwl5150-firmware iwl6000-firmware iwl6000g2a-firmware iwl6000g2b-firmware iwl6050-firmware iwl7260-firmware libertas-sd8686-firmware libertas-sd8787-firmware libertas-usb8388-firmware libertas-usb8388-olpc-firmwarelinux-firmware liquidio-firmware lulzbot-marlin-firmware lulzbot-marlin-firmware-bio lulzbot-marlin-firmware-pro midisport-firmware netronome-firmware r5u87x-firmware sigrok-firmware-filesystem sigrok-firmware-fx2lafw sigrok-firmware-nonfree uhd-firmware zd1211-firmware

# install PHP essentials
# # # # # # # # # # # # # # #
log "installing php"
install rpm-ostree php

# required modules for boris and phpctags
# # # # # # # # # # # # # # #
log "installing requried php modules for boris and phpctags"
install rpm-ostree php-json php-process

# boris (nice PHP sandbox tool)
# # # # # # # # # # # # # # #
log "installing boris"
su -c 'curl -L -O https://github.com/borisrepl/boris/releases/download/v1.0.8/boris.phar' $USER
su -c 'chmod +x boris.phar' $USER
su -c 'mv boris.phar ~/.local/bin/boris' $USER

# PHP Parallel Lint
# # # # # # # # # # # # # # #
log "installing PHP parallel lint"
sed -i "s#;phar.readonly = On#phar.readonly = Off#" /etc/php.ini
systemctl restart httpd
su -c "mkdir -p ~/lab/box-phar" $USER
su -c "cd ~/lab/box-phar && curl -LSs https://box-project.github.io/box2/installer.php | php" $USER
su -c "cp ~/lab/box-phar/box.phar ~/.local/bin/box && chmod 755 ~/.local/bin/box" $USER
su -c "git clone https://github.com/JakubOnderka/PHP-Parallel-Lint.git ~/lab/PHP-Parallel-Lint" $USER
su -c "cd ~/lab/PHP-Parallel-Lint && composer install" $USER
su -c "cp ~/lab/PHP-Parallel-Lint/parallel-lint ~/lab/PHP-Parallel-Lint/parallel-lint.php" $USER
su -c "cd ~/lab/PHP-Parallel-Lint && box build" $USER
su -c "cp /var/home/$USER/lab/PHP-Parallel-Lint/parallel-lint.phar ~/.local/bin/parallel-lint && chmod 755 ~/.local/bin/parallel-lint" $USER

# Support Software
log "installing support software"
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
su -c "flatpak install -y fedora org.libreoffice.LibreOffice" $USER
su -c "flatpak install -y fedora org.gimp.GIMP" $USER
su -c "flatpak install -y flathub com.nextcloud" $USER
su -c "flatpak install -y flathub com.spotify.Client" $USER
su -c "flatpak install -y flathub org.signal.Signal" $USER
su -c "flatpak install -y flathub us.zoom.Zoom" $USER
su -c "flatpak install -y flathub org.musescore.MuseScore" $USER

# Install Browsers
log "installing browsers"
install rpm-ostree chromium-freeworld firefox-x11 

# install Vagrant and Virtualbox
# Warning: Secure boot may need to be disabled
log "installing Vagrant and Virtualbox"
install rpm-ostree akmods vagrant VirtualBox virtualbox-guest-additions kernel-devel
firewall-cmd --permanent --zone=public --add-port=9041/tcp
setsebool -P httpd_can_network_connect on
semanage port -a -t http_port_t -p tcp 9041 # xdebug
usermod -aG vboxusers $USER
akmods
systemctl restart vboxdrv.service

# Rambox
# # # # # # # # # # # # # # #
log "installing Rambox"
rpm-ostree install https://github.com/ramboxapp/community-edition/releases/download/0.7.7/Rambox-0.7.7-linux-x86_64.rpm

# Gargoyle (for sanity checks)
# # # # # # # # # # # # # # #
log "install Gargoyle"
install rpm-ostree SDL SDL_mixer SDL_sound fluidsynth
su -c 'wget -O ~/Downloads/gargoyle.rpm https://github.com/rpmsphere/x86_64/blob/master/g/gargoyle-2015-5.4.x86_64.rpm?raw=true' $USER
rpm-ostree install /var/home/$USER/Downloads/gargoyle.rpm
su -c 'cp ~/.yadrlite/awesome/garglk.ini ~/.garglkrc' $USER

# more sanity checks
install rpm-ostree install cool-retro-term bsd-games

# Chess
# # # # # # # # # # # # # # #
log "installing chess engines"
wget https://copr.fedorainfracloud.org/coprs/awood/scid_vs_pc/repo/fedora-$(rpm -E %fedora)/awood-scid_vs_pc-fedora-$(rpm -E %fedora).repo -P /etc/yum.repos.d/
install rpm-ostree scid_vs_pc.x86_64 scid_vs_pc-sounds scid_vs_pc-books
# stockfish
install rpm-ostree stockfish

# pdf support
log "installing pdf support"
install rpm-ostree cups-pdf evince pdfarranger mupdf xournal

# install locate
install rpm-ostree mlocate
updatedb

# handle ACPI wake-up settings for non-platform devices
log "handle ACPI wake-up settings for non-platform devices"
cp -f /var/home/$USER/.yadrlite/src/org/system/acpi-wake.service /etc/systemd/system
chmod 777 /etc/systemd/system/acpi-wake.service
systemctl start acpi-wake.service
systemctl enable acpi-wake.service

# permissions, status and boot configuration
# # # # # # # # # # # # # # #
log "setup permissions, status and boot configuration"
find /var/home/$USER/.config -type d -exec chmod 0755 {} \;
find /var/home/$USER/.config -type f -exec chmod 0644 {} \;
find /var/home/$USER/.config -name "*" -execdir chmod u+x {} +
install rpm-ostree plymouth-theme-spinner
plymouth-set-default-theme -R bgrt

# add manual entries
log "add application entries"
su -c 'mkdir -p ~/.local/share/applications' $USER
su -c 'touch ~/.local/share/applications/touchpad.desktop' $USER
printf '[Desktop Entry] \n' >> /var/home/$USER/.local/share/applications/touchpad.desktop
printf 'Type=Application\n' >> /var/home/$USER/.local/share/applications/touchpad.desktop
printf 'Name=Toggle Touchpad\n' >> /var/home/$USER/.local/share/applications/touchpad.desktop
printf "Exec=/var/home/$USER/.config/awesome/scripts/toggle-touchpad\n" >> /var/home/$USER/.local/share/applications/touchpad.desktop
su -c 'touch ~/.local/share/applications/mpvdvd.desktop' $USER
printf '[Desktop Entry] \n' >> /var/home/$USER/.local/share/applications/mpvdvd.desktop
printf 'Type=Application\n' >> /var/home/$USER/.local/share/applications/mpvdvd.desktop
printf 'Name=mpv Media Player DVD\n' >> /var/home/$USER/.local/share/applications/mpvdvd.desktop
printf "Exec=mpv --dvd-device=/dev/sr0 dvd:// --player-operation-mode=pseudo-gui --force-window --idle\n" >> /var/home/$USER/.local/share/applications/mpvdvd.desktop
su -c 'touch ~/.local/share/applications/mpvdvdall.desktop' $USER
printf '[Desktop Entry] \n' >> /var/home/$USER/.local/share/applications/mpvdvdall.desktop
printf 'Type=Application\n' >> /var/home/$USER/.local/share/applications/mpvdvdall.desktop
printf 'Name=mpv Media Player DVD Play All\n' >> /var/home/$USER/.local/share/applications/mpvdvdall.desktop
printf "Exec=mpv --dvd-device=/dev/sr0 dvd://0 dvd://1 dvd://2 dvd://3 dvd://4 dvd://5 dvd://6 dvd://7 dvd://8 dvd://9 --player-operation-mode=pseudo-gui --force-window --idle\n" >> /var/home/$USER/.local/share/applications/mpvdvdall.desktop
su -c 'touch ~/.local/share/applications/mpvbd.desktop' $USER
printf '[Desktop Entry] \n' >> /var/home/$USER/.local/share/applications/mpvbd.desktop
printf 'Type=Application\n' >> /var/home/$USER/.local/share/applications/mpvbd.desktop
printf 'Name=mpv Media Player Bluray\n' >> /var/home/$USER/.local/share/applications/mpvbd.desktop
printf "Exec=mpv --bluray-device=/dev/sr0 bd://\n" >> /var/home/$USER/.local/share/applications/mpvbd.desktop

# Install Multimedia Codecs
log "installing multimedia codecs"
install rpm-ostree rpmfusion-free-release-tainted 
install rpm-ostree mpv devedeng youtube-dl aria2 gstreamer1-plugins-bad-free gstreamer1-plugins-bad-free-extras gstreamer1-plugins-bad-free-fluidsynth gstreamer1-plugins-bad-free-wildmidi gstreamer1-plugins-bad-free-zbar gstreamer1-plugins-bad-freeworld gstreamer1-plugins-base gstreamer1-plugins-base-devel gstreamer1-plugins-base-tools gstreamer1-plugins-entrans gstreamer1-plugins-entrans-docs gstreamer1-plugins-fc gstreamer1-plugins-good gstreamer1-plugins-good-extras gstreamer1-plugins-good-gtk gstreamer1-plugins-good-qt gstreamer1-plugins-ugly gstreamer1-plugins-ugly-free gstreamer1-plugin-openh264 gstreamer1-libav lame lame-libs ffmpeg ffmpeg-libs compat-ffmpeg28 lsdvd libdvdnav libdvdread libdvdcss java-1.8.0-openjdk libbluray libbluray-utils libbluray-bdj
su -c "cp -r ~/.yadrlite/awesome/mpv ~/.config" $USER

# end awesome install
printf "Awesome Installation complete.  Please reboot your system."
printf "\r# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #\r"
fi

