#! /bin/sh

# Loads Hotkeys
sxhkd &

# #---Screen/Monitor Initialization---# #
primary="DP2-2"
monitor=(`xrandr --listactivemonitors | xargs -l | grep -oE '[^ ]+$'`)
bspc monitor ${monitor[1]} -d I II III IV V VI VII VIII IX X
if [ ${monitor[0]} -eq 1 ]; then
    xrandr --output ${monitor[1]} --primary
    bspc monitor ${monitor[1]} -d I II III IV V VI VII VIII IX X
    export MONITOR=${monitor[1]} && polybar primary &
else
    if [ ${monitor[2]} == $primary ]; then
        secondary=${monitor[1]}
    else
        primary=${monitor[1]}
        secondary=${monitor[2]}
    fi
    xrandr --output $primary --primary --left-of $secondary
    bspc monitor $primary -d I II III IV V VI VII VIII
    bspc monitor $secondary -d IX X
    export MONITOR=$primary && polybar primary &
    export MONITOR=$secondary && polybar secondary &
fi

# #---BSPWM Options---# #
bspc config border_width         1
bspc config window_gap           6
bspc config top_padding          6
bspc config right_padding        6
bspc config bottom_padding       6
bspc config left_padding         6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#d79921"

# #---Behavior--# #
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr

# #---Application Defaults---# #
bspc rule -a Emacs state=tiled

# #---Starting External Scripts---# #
# Starts dunst for notifications:
dunst &
# Xbanish makes the mouse invisible after a brief period
xbanish &
# simple lockout screen that leaves the machine running
xautolock -time 10 -locker "i3lock -c 507065" &
# blue-light adaptation
redshift-gtk &
# unmute microphone
amixer set Capture cap
# turn on flameshot
flameshot &
# #---Screen/Monitor Setup---# #
# repaints backgrounds
feh --randomize --bg-scale ~/Nextcloud/backgrounds/*
# This swaps Esc and Caps Lock Keys
setxkbmap -option caps:swapescape
# this example connects a bluetooth device
echo -e "connect A4:E9:75:F0:EF:87 \nquit" | bluetoothctl
# Composite manager (always load last)
xcompmgr -c -f -n &
# cleanup
wait 1.5s
# bspc desktop Desktop -r
echo XHCI > /proc/acpi/wakeup
