#! /bin/sh

# Loads Hotkeys
sxhkd &

# #---Screen/Monitor Initialization---# #
monitor=(`xrandr --listactivemonitors | xargs -l | grep -oE '[^ ]+$'`)
bspc monitor ${monitor[1]} -d I II III IV V VI VII VIII IX X

# #---BSPWM Options---# #
bspc config border_width         1
bspc config window_gap           6
bspc config top_padding          6
bspc config right_padding        6
bspc config bottom_padding       6
bspc config left_padding         6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#d79921"

# #---Behavior--# #
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr

# #---Application Defaults---# #
bspc rule -a Emacs state=tiled

# #---Starting External Scripts---# #
# Starts dunst for notifications:
dunst &
# Xbanish makes the mouse invisible after a brief period
xbanish &
# simple lockout screen that leaves the machine running
xautolock -time 10 -locker "i3lock -c 507065" &
# blue-light adaptation
redshift-gtk &
# unmute microphone
amixer set Capture cap
# turn on flameshot
flameshot &
# #---Screen/Monitor Setup---# #
~/.config/scripts/bspwm_screen_reset.sh 
# Composite manager (always load last)
xcompmgr -c -f -n &
# cleanup
wait 1.5s
bspc desktop Desktop -r
