#!/usr/bin/env bash
# This script is just a personal snapshot of my arch workstation.
# curl https://raw.githubusercontent.com/bridgesense/dotfiles/master/workstation/endeavouros-gemini > ~/install
# NOTE: There are additional settings under the troublehsooting section.
# bash install
# # # # # # # # # # # # # # #

# Options
# # # # # # # # # # # # # # #
# USER="${1:francis}"
LOGFILE='workstation-installation.log'

# Functions
# # # # # # # # # # # # # # #
function log {
  if [ -f "$LOGFILE" ]; then
    echo $1 >>$LOGFILE
  else
    echo $1 >$LOGFILE
  fi
}

function install {
  arr=("$@")
  _type=
  if [[ "$(declare -p arr)" =~ "declare -a" ]]; then
    for package in "${arr[@]}"; do
      if [[ $package == "package" ]]; then
        _type=$package
        continue
      fi
      if [[ $package == "flatpak" ]]; then
        _type=$package
        continue
      fi
      cnt=3
      pacname=$(echo $package | sed 's/^[^/]*\///')
      while [ $cnt -gt 0 ]; do
        if pacman -Qqe | grep $pacname; then
          break
        else
          if [[ $_type == "flatpak" ]]; then
            flatpak install flathub --noninteractive -y $package
            break
          else
            yay -S --noconfirm $package
          fi
        fi
        let "cnt-=1"
      done
      if ! pacman -Qqe | grep $pacname && [[ $_type != "flatpak" ]]; then
        log "There was a problem installing ${package}.  Please make sure this package exists."
      fi
    done
  else
    log "Warning! Passed variable is not an array".
  fi
}

log "installing commandline tools"
yay --noconfirm
install package extra/git-lfs extra/subversion
install package core/base-devel endeavouros/nvidia-inst
install package extra/ack extra/ctags extra/neovim
install package extra/ripgrep
install package extra/python-pynvim extra/lazygit extra/xclip
install package core/python extra/python-pip extra/ruby
install package extra/php core/perl extra/maven extra/composer
install package core/net-tools
install package extra/nmap extra/partitionmanager
install package extra/ranger extra/kitty extra/emacs extra/tmux
install package extra/imlib2
install package extra/nvtop extra/htop
install package extra/aria2 extra/yt-dlp
install package extra/zip extra/7zip extra/unrar
install package extra/clamav
install package extra/krita extra/krita-plugin-gmic
install package extra/gimp extra/gimp-plugin-gmic
install package extra/libreoffice-fresh
install package extra/webkit2gtk
install package extra/sdl2
install package extra/sdl12-compat
install package extra/sdl2_mixer extra/sdl2_ttf extra/sdl2_image extra/sdl2_net extra/sdl_sound
install package extra/sdl_mixer extra/sdl_ttf extra/sdl_image extra/sdl_net
install package extra/podman extra/buildah
install package extra/catatonit
install package extra/pdfarranger extra/simple-scan
install package extra/texlive-bin
install package extra/w3m extra/ktorrent
install package extra/zip
install package multilib/wine multilib/winetricks multilib/steam
install package multilib/lib32-libpulse multilib/lib32-wavpack
install package extra/xpra
install package extra/dosbox extra/virtualbox
install package aur/dmg2img
install package extra/chromium
install package aur/sddm-archlinux-theme-git
install package extra/kwalletmanager extra/ksshaskpass
install package aur/python311

# interactive fiction tools
install package aur/inform7-ide-git
install package aur/lectrote-bin

# codecs
install package extra/libavcodec extra/ffmpeg extra/libaacs
install package extra/cdrtools extra/cdrdao extra/dvd+rw-tools
install package extra/k3b

# setting up nodejs
install package extra/nodejs extra/yarn
install package extra/gulp extra/grunt-cli
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
sleep 5
source ~/.bashrc
nvm install v18.20.4
sleep 5
npm install --location=global --save-dev grunt-cli gulp gulp-cli csslint typescript@3.0 typescript-language-server intelephense yaml-lint eslint-plugin-toml eslint-plugin-markdown golangci-lint vscode-css-languageserver-bin js-beautify unified-language-server eslint emmet-ls babel-eslint typescript-lsp coffeescript coffeelint

# install fonts
install package extra/ttf-noto-nerd extra/ttf-firacode-nerd

# syncterm
# NOTE: Had some issues with aur version
# thanks to MeaTLoTioN for this alternative script
# https://www.erb.pw/how-to-install-syncterm-for-linux-from-source/
mkdir -p ~/lab
cd ~/lab
curl -s https://erb.pw/get-syncterm.sh | bash

# Installing configuration
# # # # # # # # # # # # # # #
log "installing custom configuration"
wget https://raw.githubusercontent.com/bridgesense/dotfiles/master/setup
bash setup
cp -f ~/.yadrlite/workstation/Xresources ~/.Xresources
cp -r ~/.yadrlite/workstation/nvim ~/.config
cp -r ~/.yadrlite/workstation/kitty ~/.config
cp -r ~/.yadrlite/workstation/ranger ~/.config
find ~/.config -type d -exec chmod 0755 {} \;
find ~/.config -type f -exec chmod 0644 {} \;
find ~/.config -name "*.sh" -execdir chmod u+x {} +

# improve sound
mkdir -p ~/.config/pipewire/pipewire.conf.d
printf "context.properties = {\n\
  default.clock.rate = 192000\n\
  default.clock.allowed-rates = [ 44100 48000 88200 96000 192000 352800 384000]\n\
}\n\
stream.properties = {\n\
  resample.quality = 10\n\
}\n\
" >>~/.config/pipewire/pipewire.conf.d/10-rates.conf

# setup kwallet
mkdir -p ~/.config/environment.d
printf "SSH_ASKPASS=/usr/bin/ksshaskpass\n\
SSH_ASKPASS_REQUIRE=prefer\n\
" >>~/.config/environment.d/ssh_askpass.conf

# Troubleshooting
# # # # # # # # # # # # # # #

# quiet startup (for systemd-boot)
# sudo sed -i '$ s/$/ quiet/' /etc/kernel/cmdline
# sudo reinstall-kernels

# quiet startup (for grub)
# sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/' /etc/default/grub
# sudo grub-mkconfig -o /boot/grub/grub.cfg

# enable ollama server
curl -fsSL https://ollama.com/install.sh | sh
sudo mkdir -p /usr/share/ollama/.ollama
sudo chown -R ollama:ollama /usr/share/ollama
# to enable ollama server on local/external networks
# vi /etc/systemd/system/ollama.service
# add this Environment under [Service] :
# Environment="OLLAMA_HOST=0.0.0.0:11434"
# sudo systemctl daemon-reload
# sudo firewall-cmd --zone=public --add-port=11434/tcp --permanent
# sudo firewall-cmd --reload
sudo systemctl enable ollama

# enable blutooth devices
sudo systemctl enable bluetooth

# clamav update
sudo freshclam

# orthography
install package extra/ttf-gentium-plus

# clip baloo file indexing
printf "first run=false \n\
only basic indexing=true \n\
" >>~/.config/baloofilerc

# lampready patch
# (run as root) echo "net.ipv4.ip_unprivileged_port_start=0" >/etc/sysctl.d/05-expose-privileged.conf
# sudo sysctl --system
# sudo firewall-cmd --zone=public --add-port=9003/tcp --permanent
# sudo firewall-cmd --reload

# nvidia support
#
# yay -S --noconfirm extra/cuda
# nvidia-inst -p --32
# prime-run <application>

# to install hp setup
# tap the wifi icon on the printer and obtain the printer's ip address
# use the ip address in the following command
# sudo hp-setup -a <ip_address>

# setting up git
# git config --global user.email "user@domain.com"
# git config --global user.name "First Last"

# installing a swap file
# fallocate -l 128G /swap
# chmod 600 /swap
# mkswap /swap
# echo "/swap none swap defaults 0 0" | sudo tee -a /etc/fstab

# change default SDDM theme
# this seems to help in situations where SDDM doesn't hand off to KDE Plasma well
sudo sed -i 's/Current=.*/Current=archlinux/' /etc/sddm.conf.d/kde_settings.conf

# clean everything
yay -Scc --noconfirm

log "Installation complete.  Please reboot your system."
printf "\r# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #\r"
printf "ALL DONE\r"
printf "Review the workstation-installation.login and address any uninstalled packages noted.\r"
printf "PLEASE REBOOT YOUR SYSTEM."
