#!/usr/bin/env bash
# crontab -e
# include the following line
# */15 * * * * /bin/bash /home/francis/.config/i3/battery >/dev/null 2>&1

BATTINFO=`apm -l`

if [[ $BATTINFO < 30 ]] ;
then
    DISPLAY=:0.0 /usr/bin/notify-send -u critical "low battery" "only $BATTINFO min left!"
fi
