#!/usr/bin/env bash
# crontab -e
# include the following line
# */15 * * * * /bin/bash /home/francis/.config/i3/battery >/dev/null 2>&1

BATTINFO=$(echo "`apm -t` / 60" | bc)

if [[ `apm -b` != 0 && `apm -b` != 3 && $BATTINFO < 30 ]] ;
then
    DISPLAY=:0.0 /usr/local/bin/notify-send -u critical "low battery" "only $BATTINFO min left!"
fi
