#!/usr/bin/env bash
# #---Starting External Scripts---# #
xset dpms force off
# Xbanish makes the mouse invisible after a brief period
xbanish &
# blue-light adaptation
redshift-gtk &
# sound setup
pacmd "load-module module-switch-on-connect"
# unmute microphone
amixer set Capture cap
# sound boost
pactl list | grep -oP 'Sink #\K([0-9]+)' | while read -r i ; do pactl -- set-sink-volume $i +3% ; done
# turn on flameshot
flameshot &
# Device discovarability
rfkill unblock 0
pactl load-module module-bluetooth-discover
# #---Screen/Monitor Setup---# #
xautolock -time 10 -locker "i3lock -c 1d2021" -detectsleep &
# Composite manager (always load last)
compton -b -c --backend glx --vsync none &
