#!/user/bin/env bash
#
# ~/.xinitrc
#
# Executed by startx

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xset +fp ~/.local/share/fonts/DejaVuSansMono &

xrdb -merge ~/.Xresources

$SHELL ~/.config/scripts/dwm-startup

exec dwm 
