#!/user/bin/env bash
#
# ~/.xinitrc
#
# Executed by startx

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

env XDG_CURRENT_DESKTOP=GNOME gnome-control-center

xrdb -merge ~/.Xresources

$SHELL ~/.config/scripts/dwm-startup

exec dwm 
