#!/usr/bin/env bash
# #---Starting External Scripts---# #
# Status bar
$SHELL ~/.config/scripts/dwm-statusbar &
# Starts dunst for notifications:
dunst &
# Xbanish makes the mouse invisible after a brief period
xbanish &
# blue-light adaptation
redshift-gtk &
# unmute microphone
amixer set Capture cap
# turn on flameshot
flameshot &
# Composite manager (always load last)
xcompmgr -c -f -n &
# Device discovarability
pactl load-module module-bluetooth-discover
# #---Screen/Monitor Setup---# #
xautolock -time 10 -locker "bash ~/.config/scripts/screen-saver" &
# repaints backgrounds
$SHELL ~/.config/scripts/screen-init
