#!/usr/bin/env bash
# #---Starting External Scripts---# #
# Status bar
$SHELL ~/.config/scripts/dwm-statusbar &
# Starts dunst for notifications:
dunst &
# Xbanish makes the mouse invisible after a brief period
xbanish &
# blue-light adaptation
redshift-gtk &
# sound setup
pacmd "load-module module-switch-on-connect"
# unmute microphone
amixer set Capture cap
# sound boost
pactl list | grep -oP 'Sink #\K([0-9]+)' | while read -r i ; do pactl -- set-sink-volume $i +3% ; done
# turn on flameshot
flameshot &
# Device discovarability
rfkill unblock 0
pactl load-module module-bluetooth-discover
# disable dpms to prevent conflict with xautolock suspend routines
xset -dpms 
# #---Screen/Monitor Setup---# #
xautolock -time 10 -locker "bash ~/.config/scripts/screen-saver" &
# repaints backgrounds
$SHELL ~/.config/scripts/screen-init
# Composite manager (always load last)
compton --backend glx --vsync none &
