#!/usr/bin/env bash
# detect swapped workstations 
pkill -f asciiquarium
pkill -f slock
setxkbmap -synch
xset dpms force off
sleep 0.5 

# kill any instance of asciiquarium
alacritty -e sh -c "wmctrl -r 'alacritty' -b add,fullscreen; asciiquarium" &
slock
pkill -f asciiquarium
bash ~/.config/scripts/screen-init 
