#!/usr/bin/env bash
# Dependency checks
if [ ! $(command -v slock) ]; then
    echo "\"command not found: \"slock\"" >&2
    exit 1
fi

# Lock screen, reset monitors and kill screen saver on unlock
slock 
bash ~/.config/scripts/screen-init 
