# list colorfix
alias ls='ls --color=auto'
export LS_COLORS=

# offers the widest compatibility on remote access
export TERM=xterm-256color

# default to nvim if installed
if [[ -n $SSH_CONNECTION || ! -x "$(command -v nvim)" ]]; then
  export EDITOR='vim'
else
  alias vi="$(which nvim)"
  alias vim="$(which nvim)"
  export EDITOR='nvim'
fi

# Default Prompt
export PS1="\[\033[0;31m\]\u \[\033[0;36m\]\w\[\033[0;0m\] "
